### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by WhiteBoardDev** [SlurpyTurts/BCC#5]
Having dependency management issues with the project. The setup files are really clunky and we are getting different results in different machines. We need to figure out how to consistently deal with project setup and dependency management.

The biggest issue we get now is "Unable to import dataaccess" even though it has a `__init__.py` and is just a subfolder.

**Comment by WhiteBoardDev** [comment]
@SlurpyTurts please add the error you get here

**Comment by WhiteBoardDev** [comment]
@srt4 If you have space time and want to get back into the python game :)

**Comment by srt4** [comment]
Checking.

**Comment by srt4** [comment]
What are the steps to repro this issue? 

I'm curious whether this is occurring on a venv environment, vanilla Python on Linux, etc.
